/** Metadata for a module demo route shown on the /demo hub. */
export interface IDemoRoute {
  href: string;
  title: string;
  description: string;
}

/** Maps module names to their demo hub entries (main route only). */
export const MODULE_DEMO_ROUTES: Record<string, IDemoRoute> = {
  'webln-payments': {
    href: '/demo/webln',
    title: 'WebLN Payments',
    description: 'Send and receive Lightning payments with WebLN.',
  },
  'nostr-identity': {
    href: '/demo/nostr',
    title: 'Nostr Identity',
    description: 'Sign in with NIP-07 and sign messages with your Nostr key.',
  },
  'ecash-balance': {
    href: '/demo/ecash',
    title: 'Ecash Balance',
    description: 'Read Fedi ecash balance and install mini app prompts.',
  },
  'payment-gated-content': {
    href: '/demo/payment-gated',
    title: 'Payment-Gated Content',
    description: 'Unlock articles and content after a Lightning payment.',
  },
  lnurl: {
    href: '/demo/lnurl',
    title: 'LNURL',
    description: 'LNURL-pay, withdraw, and auth flows with QR codes.',
  },
  'ai-chat-gated': {
    href: '/demo/ai-chat',
    title: 'Gated AI Chat',
    description: 'Pay-per-message AI chat gated by Lightning invoice.',
  },
  'ai-assistant': {
    href: '/demo/assistant',
    title: 'AI Assistant',
    description: 'Streaming AI assistant with tool use and markdown replies.',
  },
  'multispend-demo': {
    href: '/demo/multispend',
    title: 'Multispend',
    description: 'Shared wallet proposals, votes, and approval flows.',
  },
  'nostr-feed': {
    href: '/demo/nostr-feed',
    title: 'Nostr Feed',
    description: 'Publish notes, browse a relay feed, and zap posts.',
  },
};

/** Module order for consistent demo hub listing. */
export const DEMO_MODULE_ORDER = [
  'webln-payments',
  'nostr-identity',
  'ecash-balance',
  'payment-gated-content',
  'lnurl',
  'ai-chat-gated',
  'ai-assistant',
  'multispend-demo',
  'nostr-feed',
] as const;

/**
 * Build demo route entries for the selected modules.
 */
export function buildDemoRoutes(moduleNames: string[]): IDemoRoute[] {
  const routes: IDemoRoute[] = [];

  for (const moduleName of DEMO_MODULE_ORDER) {
    if (!moduleNames.includes(moduleName)) continue;
    const route = MODULE_DEMO_ROUTES[moduleName];
    if (route) routes.push(route);
  }

  return routes;
}

/**
 * Generate `lib/demo-routes.ts` source for a scaffolded project.
 */
export function renderDemoRoutesFile(routes: IDemoRoute[]): string {
  const entries = routes
    .map(
      (route) =>
        `  {\n    href: '${route.href}',\n    title: '${route.title}',\n    description: '${route.description}',\n  }`,
    )
    .join(',\n');

  return `/** Auto-generated by create-fedi-app — do not edit manually. */
export interface IDemoRoute {
  href: string;
  title: string;
  description: string;
}

export const demoRoutes: IDemoRoute[] = [
${entries}
];
`;
}
