/** Auto-generated by create-fedi-app — replaced during scaffold. */
export interface IDemoRoute {
  href: string;
  title: string;
  description: string;
}

export const demoRoutes: IDemoRoute[] = [
  {
    href: '/demo/webln',
    title: 'WebLN Payments',
    description: 'Send and receive Lightning payments with WebLN.',
  },
  {
    href: '/demo/nostr',
    title: 'Nostr Identity',
    description: 'Sign in with NIP-07 and sign messages with your Nostr key.',
  },
  {
    href: '/demo/ecash',
    title: 'Ecash Balance',
    description: 'fediInternal mini-app discovery, list, and install prompts.',
  },
];
